# Generated by Django 4.0.4 on 2022-05-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('amounts', models.PositiveBigIntegerField()),
            ],
        ),
    ]
