# Generated by Django 3.2.9 on 2022-03-03 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_collect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collect',
        ),
    ]
