# Generated by Django 3.2.9 on 2022-02-04 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('dou', models.DateField(default=django.utils.timezone.now)),
                ('prname', models.CharField(max_length=50)),
                ('prdes', models.CharField(max_length=100)),
                ('stack', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('UI/UX', 'UI/UX'), ('Full Stack', 'Full Stack'), ('Android', 'Android'), ('Flutter', 'Flutter'), ('Other', 'Other')], max_length=100)),
                ('lang', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('C', 'C'), ('C#', 'C#'), ('PHP', 'PHP'), ('SQL', 'SQL'), ('Swift', 'Swift'), ('Other', 'Other')], max_length=100)),
                ('primg', models.ImageField(blank=True, upload_to='primg')),
                ('repo', models.CharField(max_length=100)),
                ('live', models.CharField(max_length=100, null=True)),
                ('docs', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
